### PR TITLE
Add linters.

### PR DESCRIPTION
**Pull request by dchin2**

### CODE REVIEW

**Review by andrewnguyen — COMMENTED** [review]
I don't think you're supposed to commit node_modules.

**Comment by dchin2** [comment]
Does the .gitignore cover this or should that be in a previous PR?

**Comment by andrewnguyen** [comment]
.gitignore will do this I think

**Comment by dchin2** [comment]
The .gitignore change is already in this commit

**Comment by dchin2** [comment]
ok fixed I think

**Review by andrewnguyen — APPROVED** [review]

**Pull request merged**
